In [1]:
import pandas as pd


In [11]:
file ='controversial-comments.jsonl'
# possible orient value: split, records, index, columns, and values)
# The following file is a subset of above file with the 1st 233537 lines.
dataframe = pd.read_json("controversial-comments_small.jsonl",orient="columns",lines=True)


In [1]:
dataframe.head(5)


NameError: name 'dataframe' is not defined

In [13]:
# Create function
def ToLower(string: str) -> str:
    return string.lower()


A. Convert all text to lowercase letters.


In [14]:
dataframe['lower_txt'] = [ToLower(string) for string in dataframe['txt']]
dataframe.head(5)


con                                                txt  \
0    0  Well it's great that he did something about th...   
1    0                       You are right Mr. President.   
2    0  You have given no input apart from saying I am...   
3    0  I get the frustration but the reason they want...   
4    0  I am far from an expert on TPP and I would ten...   

                                           lower_txt  
0  well it's great that he did something about th...  
1                       you are right mr. president.  
2  you have given no input apart from saying i am...  
3  i get the frustration but the reason they want...  
4  i am far from an expert on tpp and i would ten...

B. Remove all punctuation from the text.

In [15]:
# Load libraries
import unicodedata
import sys

# Create a dictionary of punctuation characters
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
                            if unicodedata.category(chr(i)).startswith('P'))

# For each string, remove any punctuation characters


dataframe['NoPunctxt'] = [string.translate(punctuation) for string in dataframe['txt']]
dataframe.head(5)

con                                                txt  \
0    0  Well it's great that he did something about th...   
1    0                       You are right Mr. President.   
2    0  You have given no input apart from saying I am...   
3    0  I get the frustration but the reason they want...   
4    0  I am far from an expert on TPP and I would ten...   

                                           lower_txt  \
0  well it's great that he did something about th...   
1                       you are right mr. president.   
2  you have given no input apart from saying i am...   
3  i get the frustration but the reason they want...   
4  i am far from an expert on tpp and i would ten...   

                                           NoPunctxt  
0  Well its great that he did something about tho...  
1                         You are right Mr President  
2  You have given no input apart from saying I am...  
3  I get the frustration but the reason they want...  
4  I am far from an expert on TPP and I would ten...

C. Remove stop words.

In [22]:
# Load library
from nltk.tokenize import word_tokenize


# Tokenize words
dataframe['Tokenized'] = [word_tokenize(string) for string in dataframe['NoPunctxt']]
dataframe[['NoPunctxt','Tokenized']].head(5)

NoPunctxt  \
0  Well its great that he did something about tho...   
1                         You are right Mr President   
2  You have given no input apart from saying I am...   
3  I get the frustration but the reason they want...   
4  I am far from an expert on TPP and I would ten...   

                                           Tokenized  
0  [Well, its, great, that, he, did, something, a...  
1                   [You, are, right, Mr, President]  
2  [You, have, given, no, input, apart, from, say...  
3  [I, get, the, frustration, but, the, reason, t...  
4  [I, am, far, from, an, expert, on, TPP, and, I...

In [139]:
# Load library
from nltk.corpus import stopwords

# You will have to download the set of stop words the first time
#import nltk
#nltk.download('stopwords')

# Load stop words
stop_words = stopwords.words('english')

# Remove stop words
dataframe['NoStopWords'] = dataframe['Tokenized'].apply(lambda x: [item for item in x if item not in stop_words])
dataframe.head(5)

con                                                txt  \
0    0  well its great that he did something about tho...   
1    0                         you are right mr president   
2    0  you have given no input apart from saying i am...   
3    0  i get the frustration but the reason they want...   
4    0  i am far from an expert on tpp and i would ten...   

                                           Tokenized  \
0  [well, its, great, that, he, did, something, a...   
1                   [you, are, right, mr, president]   
2  [you, have, given, no, input, apart, from, say...   
3  [i, get, the, frustration, but, the, reason, t...   
4  [i, am, far, from, an, expert, on, tpp, and, i...   

                                         NoStopWords  
0  [well, great, something, beliefs, office, doub...  
1                             [right, mr, president]  
2  [given, input, apart, saying, wrong, argument,...  
3  [get, frustration, reason, want, way, foundati...  
4  [far, expert, tpp, would, tend, agree, lot, pr...

In [ ]:
D. Apply NLTK’s PorterStemmer.

In [23]:
# Load library
from nltk.stem.porter import PorterStemmer


# Create stemmer
porter = PorterStemmer()

# Apply stemmer
dataframe['PorterStemmer']  = dataframe['Tokenized'].apply(lambda x: [porter.stem(item) for item in x]) 

In [24]:
dataframe.head(10)


con                                                txt  \
0    0  Well it's great that he did something about th...   
1    0                       You are right Mr. President.   
2    0  You have given no input apart from saying I am...   
3    0  I get the frustration but the reason they want...   
4    0  I am far from an expert on TPP and I would ten...   
5    0  Thanks for playing. [I feel like her now](http...   
6    0                                          [deleted]   
7    0  i cant be racist, i have a black friend  \n\nl...   
8    0  Nope. You're right that they are both smoke an...   
9    0  &lt;That's exactly what it means. especially w...   

                                           lower_txt  \
0  well it's great that he did something about th...   
1                       you are right mr. president.   
2  you have given no input apart from saying i am...   
3  i get the frustration but the reason they want...   
4  i am far from an expert on tpp and i would ten...   
5  thanks for playing. [i feel like her now](http...   
6                                          [deleted]   
7  i cant be racist, i have a black friend  \n\nl...   
8  nope. you're right that they are both smoke an...   
9  &lt;that's exactly what it means. especially w...   

                                           NoPunctxt  \
0  Well its great that he did something about tho...   
1                         You are right Mr President   
2  You have given no input apart from saying I am...   
3  I get the frustration but the reason they want...   
4  I am far from an expert on TPP and I would ten...   
5  Thanks for playing I feel like her nowhttpsthe...   
6                                            deleted   
7  i cant be racist i have a black friend  \n\nlo...   
8  Nope Youre right that they are both smoke and ...   
9  ltThats exactly what it means especially when ...   

                                           Tokenized  \
0  [Well, its, great, that, he, did, something, a...   
1                   [You, are, right, Mr, President]   
2  [You, have, given, no, input, apart, from, say...   
3  [I, get, the, frustration, but, the, reason, t...   
4  [I, am, far, from, an, expert, on, TPP, and, I...   
5  [Thanks, for, playing, I, feel, like, her, now...   
6                                          [deleted]   
7  [i, cant, be, racist, i, have, a, black, frien...   
8  [Nope, Youre, right, that, they, are, both, sm...   
9  [ltThats, exactly, what, it, means, especially...   

                                       PorterStemmer  
0  [well, it, great, that, he, did, someth, about...  
1                      [you, are, right, Mr, presid]  
2  [you, have, given, no, input, apart, from, say...  
3  [I, get, the, frustrat, but, the, reason, they...  
4  [I, am, far, from, an, expert, on, tpp, and, I...  
5  [thank, for, play, I, feel, like, her, nowhttp...  
6                                            [delet]  
7  [i, cant, be, racist, i, have, a, black, frien...  
8  [nope, your, right, that, they, are, both, smo...  
9  [ltthat, exactli, what, it, mean, especi, when...

E. Use a Tf-idf vector instead of the word frequency vector.

In [32]:
# Load libraries
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
# Create text
# Here we apply vectorizer to the 1st 10 rows of the txt column. Notice the number of features increases with the number of rows
# because there are more text to process. It ay be worth which to get rid of some words 1st.
text_data = dataframe['txt'][:20]
# Create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)
# Show tf-idf feature matrix
feature_matrix.toarray()


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.26652051,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.26452993,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.16447604,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.12057085,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.14144756,
        0.08435259]])

In [33]:
tfidf.vocabulary_

{'well': 474,
 'it': 233,
 'great': 192,
 'that': 423,
 'he': 200,
 'did': 127,
 'something': 402,
 'about': 9,
 'those': 431,
 'beliefs': 60,
 'while': 481,
 'was': 469,
 'in': 219,
 'office': 306,
 'doubt': 134,
 'trump': 446,
 'would': 497,
 'fight': 161,
 'the': 424,
 'un': 450,
 'for': 168,
 'so': 398,
 'really': 355,
 'happy': 196,
 'obama': 304,
 'could': 106,
 'oh': 307,
 'wait': 465,
 'you': 502,
 'are': 37,
 'right': 375,
 'mr': 288,
 'president': 340,
 'have': 199,
 'given': 181,
 'no': 298,
 'input': 225,
 'apart': 34,
 'from': 176,
 'saying': 382,
 'am': 26,
 'wrong': 498,
 'argument': 39,
 'clearly': 89,
 'get': 179,
 'frustration': 177,
 'but': 73,
 'reason': 356,
 'they': 428,
 'want': 466,
 'them': 425,
 'to': 438,
 'do': 130,
 'way': 470,
 'is': 231,
 'because': 53,
 'its': 234,
 'foundation': 172,
 'more': 284,
 'complex': 98,
 'problems': 343,
 'as': 41,
 'advance': 17,
 'grades': 191,
 'can': 78,
 'decent': 117,
 'grade': 190,
 'on': 309,
 'an': 29,
 'sat': 379,
 '

5.3 Encoding Dictionaries of Features

In [34]:
# Import library
from sklearn.feature_extraction import DictVectorizer

In [35]:
# Create dictionary
data_dict = [{"Red": 2, "Blue": 4},
             {"Red": 4, "Blue": 3},
             {"Red": 1, "Yellow": 2},
             {"Red": 2, "Yellow": 2}]


In [36]:
# Create dictionary vectorizer
# By default DictVectorizer outputs a sparse matrix that only stores elements with a value other than 0. 
# This can be very helpful when we have massive matrices (often encountered in natural language processing) and want to 
# minimize the memory requirements. We can force DictVectorizer to output a dense matrix using sparse=False.

dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary to feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [37]:
# We can get the names of each generated feature using the get_feature_names method: # Get feature names
feature_names = dictvectorizer.get_feature_names()

# View feature names
feature_names


['Blue', 'Red', 'Yellow']

In [38]:
# While not necessary, for the sake of illustration we can create a pandas DataFrame to view the output better: 
# Create dataframe from features
pd.DataFrame(features, columns=feature_names)


Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

In [39]:
# Create word counts dictionaries for four documents
doc_1_word_count = {"Red": 2, "Blue": 4}
doc_2_word_count = {"Red": 4, "Blue": 3}
doc_3_word_count = {"Red": 1, "Yellow": 2}
doc_4_word_count = {"Red": 2, "Yellow": 2}

In [40]:
# Create list
doc_word_counts = [doc_1_word_count,
                   doc_2_word_count,
                   doc_3_word_count,
                   doc_4_word_count]

# Convert list of word count dictionaries into feature matrix
dictvectorizer.fit_transform(doc_word_counts) 
# In our toy example there are only three unique words (Red, Yellow, Blue) so there are only three features in our matrix; 
# however, you can imagine that if each document was actually a book in a university library our feature matrix would be very 
# large (and then we would want to set spare to True).


array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

6.9 Weighting Word Importance


In [41]:
# Load libraries
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# Create text
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# Create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

# Show tf-idf feature matrix
feature_matrix


<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [42]:
# Show tf-idf feature matrix as dense matrix
feature_matrix.toarray()


array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [43]:
# Show feature names
tfidf.vocabulary_


{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

6.4 Tokenizing Text


In [44]:
# Tokenize by word
# Load library
from nltk.tokenize import word_tokenize

# Create text
string = "The science of today is the technology of tomorrow    "

# Tokenize words
word_tokenize(string)


['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [46]:
# Tokenize by sentence
# Load library
from nltk.tokenize import sent_tokenize

# Create text
string = "The science of today is the technology of tomorrow. Tomorrow is today."

# Tokenize sentences
sent_tokenize(string)


['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

6.7 Tagging Parts of Speech 

In [45]:
# Load libraries
from nltk import pos_tag
from nltk import word_tokenize

# Create text
text_data = "Chris loved outdoor running"
word_tokenize(text_data)
# Use pre-trained part of speech tagger
text_tagged = pos_tag(word_tokenize(text_data))

# Show parts of speech
text_tagged


[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

The output is a list of tuples with the word and the tag of the part of speech. NLTK uses the Penn Treebank parts for speech tags. Some examples of the Penn Treebank tags are:

NNP Proper noun, singular 
NN Noun, singular or mass 
RB Adverb 
VBD Verb, past tense 
VBG Verb, gerund or present participle 
JJ Adjective 
PRP Personal pronoun

Once the text has been tagged, we can use the tags to find certain parts of speech. For example, here are all nouns: # Filter words


In [47]:
[word for word, tag in text_tagged if tag in ['NN','NNS','NNP','NNPS'] ]


['Chris']

A more realistic situation would be that we have data where every observation contains a tweet and we want to convert those sentences into features for individual parts of speech (e.g., a feature with 1 if a proper noun is present, and 0 otherwise):

In [48]:
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer
# Create text
tweets = ["I am eating a burrito for breakfast",
          "Political science is an amazing field",
          "San Francisco is an awesome city"]

# Create list
tagged_tweets = []

# Tag each word and each tweet
for tweet in tweets:
    tweet_tag = pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

tagged_tweets


[['PRP', 'VBP', 'VBG', 'DT', 'NN', 'IN', 'NN'],
 ['JJ', 'NN', 'VBZ', 'DT', 'JJ', 'NN'],
 ['NNP', 'NNP', 'VBZ', 'DT', 'JJ', 'NN']]

In [49]:
# Use one-hot encoding to convert the tags into features

one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)


array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [50]:
one_hot_multi.classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

In [51]:
# Load library
import nltk
nltk.download('brown') # Download Brown Corpus
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

# Get some text from the Brown Corpus, broken into sentences
sentences = brown.tagged_sents(categories='news')

# Split into 4000 sentences for training and 623 for testing
train = sentences[:4000]
test = sentences[4000:]
print(len(sentences))
print(len(train))
print(len(test))


[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\safar\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


4623
4000
623


In [52]:
# Create backoff tagger
unigram = UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
trigram = TrigramTagger(train, backoff=bigram)

# Show accuracy
trigram.evaluate(test)

0.8174734002697437

7.6 Encoding Days of the Week 

In [53]:
# Load library
import pandas as pd

# Create dates
dates = pd.Series(pd.date_range("2/2/2002", periods=3, freq="M"))

# Show days of the week
dates.dt.day_name()


0    Thursday
1      Sunday
2     Tuesday
dtype: object

In [54]:
# If we want the output to be a numerical value and therefore more usable as a machine learning feature, 
# we can use weekday where the days of the week are represented as an integer (Monday is 0): # Show days of the week
dates.dt.weekday


0    3
1    6
2    1
dtype: int64

Knowing the weekday can be helpful if, for instance, we wanted to compare total sales on Sundays for the past three years. pandas makes creating a feature vector containing weekday information easy.
